/**
 * Step 3: Convert hei_enriched.json → appends new entries to universities.js
 *
 * Run: node scripts/importToUniDB.mjs [--min-rank 800] [--dry-run]
 * Input:  scripts/hei_enriched.json
 * Output: src/data/universitiesExpanded.js (new file, imported alongside universities.js)
 *
 * Flags:
 *   --min-rank 800   Only import universities ranked ≤ 800 (default: all)
 *   --dry-run        Print stats without writing files
 *   --top-only       Only import if rank > 0 (i.e. in QS top 1000)
 */

import { readFileSync, writeFileSync, existsSync } from 'fs';

const args = process.argv.slice(2);
const DRY_RUN  = args.includes('--dry-run');
const TOP_ONLY = args.includes('--top-only');
const minRankIdx = args.indexOf('--min-rank');
const MIN_RANK = minRankIdx !== -1 ? parseInt(args[minRankIdx + 1]) : Infinity;

// Read existing IDs to avoid duplicates
const existingRaw = readFileSync('src/data/universities.js', 'utf8');
const existingIds = (existingRaw.match(/^\[(\d+),/gm) || []).map(m => parseInt(m.slice(1)));
const maxId = Math.max(...existingIds);
console.log(`Existing DB: ${existingIds.length} universities, max ID: ${maxId}`);

if (!existsSync('scripts/hei_enriched.json')) {
  console.error('hei_enriched.json not found. Run enrichWithClaude.mjs first.');
  process.exit(1);
}

const enriched = JSON.parse(readFileSync('scripts/hei_enriched.json', 'utf8'));
console.log(`Enriched: ${enriched.length} institutions\n`);

// Quality filters
function isValid(u) {
  if (!u.nameEn || !u.city || !u.lat || !u.lng) return false;
  if (typeof u.lat !== 'number' || typeof u.lng !== 'number') return false;
  if (u.lat < 30 || u.lat > 72 || u.lng < -30 || u.lng > 50) return false; // Europe bounds
  if (!u.tuition || !Array.isArray(u.tuition) || u.tuition.length !== 2) return false;
  if (!u.fields || !Array.isArray(u.fields) || u.fields.length === 0) return false;
  return true;
}

let filtered = enriched.filter(isValid);
console.log(`Valid (coords + fields): ${filtered.length}`);

if (TOP_ONLY) {
  filtered = filtered.filter(u => u.rank > 0);
  console.log(`After --top-only filter: ${filtered.length}`);
}
if (MIN_RANK < Infinity) {
  filtered = filtered.filter(u => u.rank > 0 && u.rank <= MIN_RANK);
  console.log(`After --min-rank ${MIN_RANK}: ${filtered.length}`);
}

// Sort by rank (ranked first, then unranked alphabetically)
filtered.sort((a, b) => {
  if (a.rank > 0 && b.rank > 0) return a.rank - b.rank;
  if (a.rank > 0) return -1;
  if (b.rank > 0) return 1;
  return a.nameEn.localeCompare(b.nameEn);
});

console.log(`\nWill import: ${filtered.length} universities`);

if (DRY_RUN) {
  console.log('\n--- DRY RUN: Sample of first 10 entries ---');
  filtered.slice(0, 10).forEach((u, i) => {
    console.log(`${maxId + i + 1}. ${u.nameEn} (${u.country_bg}, ${u.city}) rank:${u.rank} tuition:€${u.tuition[0]}-${u.tuition[1]}`);
  });
  console.log('\nRe-run without --dry-run to write files.');
  process.exit(0);
}

// Build JS rows in the same format as universities.js
function escStr(s) {
  return (s || '').replace(/"/g, '\\"').replace(/\n/g, ' ');
}

const rows = filtered.map((u, i) => {
  const id     = maxId + i + 1;
  const name   = escStr(u.name_orig || u.nameEn);
  const nameEn = escStr(u.nameEn);
  const country= escStr(u.country_bg);
  const city   = escStr(u.city);
  const rank   = u.rank || 1500;
  const students = u.students || 10000;
  const founded  = u.founded || 1900;
  const tMin   = u.tuition[0];
  const tMax   = u.tuition[1];
  const fields = JSON.stringify(u.fields || []);
  const rating = parseFloat((u.rating || 4.0).toFixed(1));
  const accept = u.acceptance || 50;
  const intl   = u.international || 10;
  const emoji  = escStr(u.emoji || '🎓');
  const type   = u.type === 'v' ? 'v' : 'p';
  const col    = u.costOfLiving || 700;
  const emp    = u.employability || 70;
  const progs  = JSON.stringify((u.programs || []).slice(0, 6));
  const lat    = parseFloat(u.lat.toFixed(4));
  const lng    = parseFloat(u.lng.toFixed(4));

  return `[${id},"${name}","${nameEn}","${country}","${city}",${rank},${students},${founded},[${tMin},${tMax}],${fields},${rating},${accept},${intl},"${emoji}","${type}",${col},${emp},${progs},[${lat},${lng}]]`;
});

const output = `// Auto-generated by scripts/importToUniDB.mjs
// HEI API (European University Foundation) + Claude enrichment
// Generated: ${new Date().toISOString()}
// Institutions: ${rows.length}

const rawHEI=[
${rows.join(',\n')}
];

export default rawHEI;
`;

writeFileSync('src/data/universitiesExpanded.js', output);
console.log(`\nWrote ${rows.length} universities → src/data/universitiesExpanded.js`);

// Print country breakdown
const byCountry = {};
filtered.forEach(u => {
  byCountry[u.country_bg] = (byCountry[u.country_bg] || 0) + 1;
});
console.log('\nBreakdown by country:');
Object.entries(byCountry)
  .sort((a, b) => b[1] - a[1])
  .forEach(([c, n]) => console.log(`  ${c}: ${n}`));

console.log('\nNext step: update src/data/universities.js to import universitiesExpanded.js');
console.log('See the comment at the bottom of this file for the merge snippet.');

/*
--- MERGE SNIPPET ---
In src/data/universities.js, add at the bottom:

import rawHEI from './universitiesExpanded.js';

const heiMapped = rawHEI.map(r => ({
  id:r[0], name:r[1], nameEn:r[2], country:r[3], city:r[4],
  rank:r[5], students:r[6], founded:r[7], tuition:r[8],
  fields:r[9], rating:r[10], acceptance:r[11], international:r[12],
  emoji:r[13], type:r[14]==="p"?"public":"private", costOfLiving:r[15],
  employability:r[16], programs:r[17], coords:r[18],
  dorms:r[14]==="p", scholarships:r[10]>=4.0||r[8][0]===0,
  languages:r[3]==="UK"||r[3]==="Ирландия"?["Английски"]:["Английски","Local"]
}));

export const universities = [...existingUniversities, ...heiMapped];
---
*/
